import { NextResponse } from "next/server";
import { errorResponse } from "@/lib/api-helpers";
import { getCurrentUser } from "@/lib/session";
import { canAccessResource } from "@/lib/access";
import { findAuthorById, findResourceById, logDownload } from "@/lib/store";

export const dynamic = "force-dynamic";

export async function POST(_req: Request, ctx: RouteContext<"/api/resources/[id]/download">) {
  const { id } = await ctx.params;
  const resource = findResourceById(id);
  if (!resource) return errorResponse(404, "not_found", "Resource not found.");

  const user = await getCurrentUser();
  const access = canAccessResource(user, resource);
  if (!user || !access.allowed) {
    return errorResponse(403, "forbidden", access.reason ?? "You cannot download this resource.");
  }

  logDownload(user.id, resource.id);

  const author = findAuthorById(resource.author_id);
  const content = [
    resource.title,
    `by ${author?.name ?? "Unknown author"} (${resource.publication_year})`,
    "=".repeat(60),
    "",
    resource.description,
    "",
    "This is a placeholder demo file generated by SmartLib for training",
    "purposes. No copyrighted content is distributed by this platform.",
    `Access type: ${resource.access_type} | ISBN: ${resource.isbn}`,
  ].join("\n");

  return new NextResponse(content, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${resource.id}-demo.txt"`,
    },
  });
}
